name: MAUI Unit Tests

on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workloads
        run: dotnet workload install maui-android

      - name: Restore dependencies (Windows + Android)
        run: dotnet restore

      - name: Build Windows app
        run: dotnet build --configuration Release -f net8.0-windows10.0.19041.0 --runtime win-x64

      - name: Build Android app
        run: dotnet build --configuration Release -f net8.0-android

      - name: Run unit tests (Windows)
        run: dotnet test --configuration Release -f net8.0-windows10.0.19041.0 --no-restore --no-build --verbosity normal
